
CATEGORY_MAP = {
    # 1. 魚類・爬虫類を除く動物（哺乳類・鳥類・昆虫など）
    "Animal (category)": [s.lower() for s in [
        "tench", "goldfish", "great_white_shark", "tiger_shark", "hammerhead",
        "cock", "hen", "ostrich", "brambling", "goldfinch", "house_finch", "junco",
        "indigo_bunting", "robin", "bulbul", "jay", "magpie", "chickadee", "water_ouzel",
        "kite", "bald_eagle", "vulture", "great_grey_owl", "european_fire_salamander",
        "common_newt", "eft", "spotted_salamander", "axolotl", "bullfrog", "tree_frog",
        "tailed_frog", "banded_gecko", "common_iguana", "american_chameleon", "whiptail",
        "agama", "frilled_lizard", "alligator_lizard", "gila_monster", "green_lizard",
        "african_chameleon", "komodo_dragon", "african_crocodile", "american_alligator",
        "thunder_snake", "ringneck_snake", "hognose_snake", "green_snake", "king_snake",
        "garter_snake", "vine_snake", "night_snake", "boa_constrictor", "rock_python",
        "indian_cobra", "green_mamba", "horned_viper", "diamondback", "sidewinder",
        "harvestman", "scorpion", "black_and_gold_garden_spider", "barn_spider",
        "garden_spider", "black_widow", "tarantula", "wolf_spider", "centipede",
        "black_grouse", "ptarmigan", "ruffed_grouse", "prairie_chicken", "peacock", "quail",
        "partridge", "african_grey", "macaw", "sulphur-crested_cockatoo", "lorikeet",
        "coucal", "bee_eater", "hornbill", "hummingbird", "jacamar", "toucan", "drake",
        "red-breasted_merganser", "goose", "black_swan", "tusker", "echidna", "platypus",
        "wallaby", "koala", "wombat", "snail", "slug", "white_stork", "black_stork",
        "spoonbill", "flamingo", "little_blue_heron", "american_egret", "bittern", "crane",
        "limpkin", "european_gallinule", "american_coot", "bustard", "ruddy_turnstone",
        "red-backed_sandpiper", "redshank", "dowitcher", "oystercatcher", "pelican",
        "king_penguin", "albatross", "chihuahua", "japanese_spaniel", "maltese_dog",
        "pekinese", "shih-tzu", "blenheim_spaniel", "papillon", "toy_terrier",
        "rhodesian_ridgeback", "afghan_hound", "basset", "beagle", "bloodhound", "bluetick",
        "black-and-tan_coonhound", "walker_hound", "english_foxhound", "redbone", "borzoi",
        "irish_wolfhound", "italian_greyhound", "whippet", "ibizan_hound",
        "norwegian_elkhound", "otterhound", "saluki", "scottish_deerhound", "weimaraner",
        "staffordshire_bullterrier", "american_staffordshire_terrier", "bedlington_terrier",
        "border_terrier", "kerry_blue_terrier", "irish_terrier", "norfolk_terrier",
        "norwich_terrier", "yorkshire_terrier", "wire-haired_fox_terrier", "lakeland_terrier",
        "sealyham_terrier", "airedale", "cairn", "australian_terrier", "dandie_dinmont",
        "boston_bull", "miniature_schnauzer", "giant_schnauzer", "standard_schnauzer",
        "scotch_terrier", "tibetan_terrier", "silky_terrier", "soft-coated_wheaten_terrier",
        "west_highland_white_terrier", "lhasa", "flat-coated_retriever",
        "curly-coated_retriever", "golden_retriever", "labrador_retriever",
        "chesapeake_bay_retriever", "german_short-haired_pointer", "vizsla",
        "english_setter", "irish_setter", "gordon_setter", "brittany_spaniel", "clumber",
        "english_springer", "welsh_springer_spaniel", "cocker_spaniel", "sussex_spaniel",
        "irish_water_spaniel", "kuvasz", "schipperke", "groenendael", "malinois", "briard",
        "kelpie", "komondor", "old_english_sheepdog", "shetland_sheepdog", "collie",
        "border_collie", "bouvier_des_flandres", "rottweiler", "german_shepherd", "doberman",
        "miniature_pinscher", "greater_swiss_mountain_dog", "bernese_mountain_dog",
        "appenzeller", "entlebucher", "boxer", "bull_mastiff", "tibetan_mastiff",
        "french_bulldog", "great_dane", "saint_bernard", "eskimo_dog", "malamute",
        "siberian_husky", "dalmatian", "affenpinscher", "basenji", "pug", "leonberg",
        "newfoundland", "great_pyrenees", "samoyed", "pomeranian", "chow", "keeshond",
        "brabancon_griffon", "pembroke", "cardigan", "toy_poodle", "miniature_poodle",
        "standard_poodle", "mexican_hairless", "timber_wolf", "white_wolf", "red_wolf",
        "coyote", "dingo", "dhole", "african_hunting_dog", "hyena", "red_fox", "kit_fox",
        "arctic_fox", "grey_fox", "tabby", "tiger_cat", "persian_cat", "siamese_cat",
        "egyptian_cat", "cougar", "lynx", "leopard", "snow_leopard", "jaguar", "lion",
        "tiger", "cheetah", "brown_bear", "american_black_bear", "polar_bear", "sloth_bear",
        "mongoose", "meerkat", "tiger_beetle", "ladybug", "ground_beetle", "long-horned_beetle",
        "leaf_beetle", "dung_beetle", "rhinoceros_beetle", "weevil", "fly", "bee", "ant",
        "grasshopper", "cricket", "walking_stick", "cockroach", "mantis", "cicada",
        "leafhopper", "lacewing", "dragonfly", "damselfly", "admiral", "ringlet", "monarch",
        "cabbage_butterfly", "sulphur_butterfly", "lycaenid", "wood_rabbit", "hare", "angora",
        "hamster", "porcupine", "fox_squirrel", "marmot", "beaver", "guinea_pig", "sorrel",
        "zebra", "hog", "wild_boar", "warthog", "ox", "water_buffalo", "bison", "ram",
        "bighorn", "ibex", "hartebeest", "impala", "gazelle", "arabian_camel", "llama",
        "weasel", "mink", "polecat", "black-footed_ferret", "otter", "skunk", "badger",
        "armadillo", "three-toed_sloth", "orangutan", "gorilla", "chimpanzee", "gibbon",
        "siamang", "guenon", "patas", "baboon", "macaque", "langur", "colobus",
        "proboscis_monkey", "marmoset", "capuchin", "howler_monkey", "titi", "spider_monkey",
        "squirrel_monkey", "madagascar_cat", "indri", "indian_elephant", "african_elephant",
        "lesser_panda", "giant_panda", "sulphur-crested_cockato","ice_bear","dogsled"
    ]],

    # 2. スポーツ（競技・選手・用具すべてを含む）
    "Sports (category)": [s.lower() for s in [
        "balance_beam", "barbell", "baseball", "basketball", "bobsled", "bow",
        "croquet ball", "dumbbell", "horizontal bar", "jersey", "knee_pad",
        "parallel bars", "ping-pong ball", "pool table", "puck", "punching_bag",
        "racket", "rugby ball", "scoreboard", "ski", "soccer_ball", "tennis ball",
        "vault", "volleyball","ballplayer", "football_helmet","golf_ball",
        "golfcart","ping_pong_ball","rugby_ball","tennis_ball","ski_mask","snowmobile",
        "croquet_ball","parallel_bars","punching_bag","table_tennis","bathing_cap",
        "horizontal_bar",
    ]],

    # 3. 機械・人工物（移動体・家電・工具・大型構造物など）
    "Machine (category)": [s.lower() for s in [
        "abacus", "aircraft_carrier", "airliner", "airship", "ambulance", "computer_keyboard",
        "container_ship", "convertible", "crane", "desktop_computer", "dial_telephone",
        "digital_clock", "digital_watch", "dishwasher", "drilling_platform", "electric_fan",
        "electric guitar", "electric locomotive", "espresso maker", "ipod", "iron", "jeep",
        "joystick", "laptop", "lawn mower", "lifeboat", "limousine", "liner", "loudspeaker",
        "lumbermill", "microphone", "microwave", "minibus", "minivan", "missile", "photocopier",
        "pickup", "polaroid camera", "police van", "power drill", "printer", "projectile",
        "projector", "racer", "radio", "radio telescope", "recreational vehicle", "reflex camera",
        "refrigerator", "remote control", "rotisserie", "school bus", "schooner", "sewing machine",
        "slot", "snowmobile", "snowplow", "solar dish", "space bar", "space heater",
        "space shuttle", "speedboat", "sports car", "spotlight", "steam locomotive", "stopwatch",
        "stove", "streetcar", "submarine", "tank", "tape player", "television", "thresher",
        "toaster", "torch", "tow truck", "tractor", "trailer truck", "trimaran", "trolleybus",
        "turnstile", "typewriter keyboard", "upright", "vacuum", "vending machine", "waffle_iron",
        "wall clock", "warplane", "washer", "wing", "yawl", "traffic light","aircraft_carrier",
        "fire_engine","cab","trailer_truck","sports_car","forklift","lawn_mower","desktop_computer",
        "remote_control","rocket","police_van","oven","washing_machine","dryer","air_conditioner",
        "humidifier","electric_fan","coffee_maker", "espresso","blender","mixing_bowl","home_theater",
        "sewing_machine","switch","cash_machine","screen","recreational_vehicle","vending_machine",
        "soap_dispenser","cassette_player","scale","monitor","tape_player","oscilloscope","hard_disc",
        "space bar","guillotine","CD_player","modem","reflex_camera","pay-phone","safe","gas_pump",
        "mailbox","ashcan","parking_meter","padlock","washbasin","espresso_maker","can_opener",
        "corkscrew","pencil_sharpener","hook","power_drill"
    ]],


    # 4. 花・景観（自然物＋植物＋海洋生物＋建造物）
    "Landscape (category)": [s.lower() for s in [
        "loggerhead", "leatherback turtle", "mud_turtle", "terrapin", "box_turtle", "electric_ray",
        "stingray", "sea_snake", "jellyfish", "sea_anemone", "brain_coral", "conch", "sea_slug",
        "chiton", "chambered nautilus", "dungeness crab", "rock_crab", "fiddler_crab", "king_crab",
        "american_lobster", "spiny_lobster", "crayfish", "hermit_crab", "isopod", "grey_whale",
        "killer_whale", "dugong", "sea_lion", "apiary", "breakwater", "beacon", "birdhouse",
        "boathouse", "butcher_shop", "cliff_dwelling", "dam", "dock", "dome", "library", "megalith",
        "planetarium", "prison", "restaurant", "shoe shop", "shoji", "sliding door", "spider web",
        "steel_arch_bridge", "stone_wall", "stupa", "suspension_bridge", "thatch", "tile_roof",
        "tobacco_shop", "totem_pole", "toyshop", "triumphal_arch", "viaduct", "water_tower",
        "worm_fence", "wreck", "yurt", "street_sign", "head_cabbage", "broccoli", "cauliflower",
        "zucchini", "spaghetti_squash", "acorn_squash", "butternut_squash", "cucumber",
        "artichoke", "bell_pepper", "cardoon", "mushroom", "granny_smith", "strawberry", "orange",
        "lemon", "fig", "pineapple", "banana", "jackfruit", "custard_apple", "pomegranate", "hay",
        "rapeseed","sea_slug","ant","sea_anemone","coral_fungus","daisy","starfish","lakeside",
        "volcano","alp", "boathouse","valley","geyser","seashore","mountain_tent","yellow_lady's_slipper",
        "rose_hip","coral_reef","promontory","sandbar","tick",
    ]],
    
    "Human (category)": [s.lower() for s in [
        "Bouvier_des_Flandres", "French_horn", "abaya", "academic_gown", "accordion", "ballplayer", "barber_chair", "barbershop", 
        "bassoon", "bath_towel", "bathing_cap", "bearskin", "bikini", "bonnet", "book_jacket", "bow_tie", 
        "brassiere", "breastplate", "caldron", "cloak", "comic_book", "cuirass", "electric_fan", "face_powder", 
        "feather_boa", "flute", "fur_coat", "giant_panda", "gorilla", "guillotine", "hair_slide", "hair_spray", 
        "hay", "hoopskirt", "kimono", "lab_coat", "leatherback_turtle", "lipstick", "maillot", "mask", 
        "microphone", "mortarboard", "neck_brace", "necklace", "oboe", "overskirt", "pajama", "panpipe", 
        "perfume", "pick", "pickelhaube", "pinwheel", "poncho", "safety_pin", "sax", "seat_belt", 
        "shield", "shower_cap", "ski_mask", "stethoscope", "stole", "suit", "sweatshirt", "trench_coat", 
        "triceratops", "trilobite", "trombone", "velvet", "vestment", "wig", "wool"
    ]],
}
