# Generated by Django 5.2.2 on 2025-07-07 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MstImages',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False, verbose_name='image_id')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded_at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Mst Image',
                'verbose_name_plural': 'Mst Images',
            },
        ),
        migrations.CreateModel(
            name='TransAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False, verbose_name='analysis_id')),
                ('model_name', models.CharField(max_length=20, verbose_name='model_name')),
                ('use_category', models.BooleanField(default=False, verbose_name='use_category')),
                ('status', models.CharField(choices=[('準備中', '準備中'), ('解析中', '解析中'), ('成功', '解析成功'), ('失敗', '解析失敗')], default='準備中', max_length=10, verbose_name='status')),
                ('label', models.CharField(max_length=20, null=True, verbose_name='label')),
                ('top_preds', models.JSONField(blank=True, null=True, verbose_name='top_predictions')),
                ('reliability', models.FloatField(null=True, verbose_name='reliability')),
                ('started_at', models.DateTimeField(null=True, verbose_name='started_at')),
                ('ended_at', models.DateTimeField(null=True, verbose_name='ended_at')),
                ('error_log', models.TextField(null=True, verbose_name='error_log')),
                ('error_name', models.CharField(max_length=20, null=True, verbose_name='error_name')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.mstimages', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Trans Analysis',
                'verbose_name_plural': 'Trans Analyses',
            },
        ),
    ]
